### ISSUE TITLE
[BUG] Beat saber crashes on map loading

### ISSUE THREAD

**Issue by ICEDStriker** [Goobwabber/MultiplayerCore#16]
**MultiplayerCore Version and Download Source**
1.0.0 Github

**Your Platform**
PC, Valve Index

**Describe the bug**
I dont know if its this mod or Beattogether.

When i play a Map in Multiplayer that i dont have installed alreedy the game locks up and i have to restart the game. The weird thing is that the map downloads in the custommultiplayerlevels folderand works when i restarted the game.
when i already have the map installed it works.
these are the only mods i have installed right now
![grafik](https://user-images.githubusercontent.com/32615790/173098006-a6137830-d719-42c3-bb9d-0facd8a5d152.png)

**To Reproduce**

1. Go in a Lobby in online mode with a friend
2. let him choose a map you dont have installed
3. click ready
4. enjoy a freezed game

**Expected behavior**
the map downloads and i can play

**Log**
log file is attached. [2022.06.10.13.19.53.log](https://github.com/Goobwabber/MultiplayerCore/files/8878511/2022.06.10.13.19.53.log)
In the session where the log file is from i first played a map i alredy had end then one that i dont had installed.

**Screenshots/Video**

**Additional context**
i have made a clean install of beat saber and even windows (not because of the multiplayer bug) and deleted the hyperbolic magnetism folder in appdata but that didnt help.

**Comment by JRCtr** [comment]
Seems to be an issue with some of Beatsaber+'s modules, got multiplayer working by disabling all modules except chat

**Comment by Goobwabber** [comment]
old i assume? haven't received any issues of bs+ causing issues in multi recently
