### ISSUE TITLE
[TODO] Download progress bar

### ISSUE THREAD

**Issue by Goobwabber** [Goobwabber/MultiplayerCore#2]
add a download progress bar

**Comment by michael-r-elp** [comment]
I would consider this done, since that features has been implemented since August 2022 see 5c8601f2228cfadcc6751e04847434631a88e9ef

**Comment by michael-r-elp** [comment]
Closing issue, since feature has been implemented in 5c8601f2228cfadcc6751e04847434631a88e9ef
