### ISSUE TITLE
Being in menu during map start soft locks UI[BUG] 

### ISSUE THREAD

**Issue by whymoo** [Goobwabber/MultiplayerCore#22]
**MultiplayerCore Version and Download Source**

Multiple, happens on patreon 1.1.2, but has happened as far back as game version 1.16 

**Your Platform**

PC/Steam, -vrmode oculus, cv1

**Describe the bug**

If any kind of menu is open that replaces the default multi menus, BetterSongSearch, the new MultiplayerExtensions, BSPlus stuff,  when the game switches from lobby to map, you will be stuck in that menu and no buttons will work when you return to lobby

**To Reproduce**

1. Open multi
2. Open BetterSongSearch
3. Wait for host to start map
4. Wait until you return to lobby
5. Try to press any button, they won't work

**Expected behavior**
Either menu automatically closes on map start or you can still use it on map end

**Log**
[_latest.log](https://github.com/Goobwabber/MultiplayerCore/files/9210361/_latest.log)

**Comment by Goobwabber** [comment]
Report these bugs to the makers of the problem mods, this isn't a bug with mpcore
