### ISSUE TITLE
[BUG] Can't play in 1.27.0 anymore.

### ISSUE THREAD

**Issue by Tarroook** [Goobwabber/MultiplayerCore#40]
**MultiplayerCore Version and Download Source**
1.1.2

**Your Platform**
PC, Beat Saber 1.27.0 (downgraded on purpose)

**Describe the bug**
When trying to play in multiplayer, a message that says to upgrade to 1.2.0 displays. 
If I upgrade to 1.2.0, a message to upgrade beat saber to 1.28.0 appears.

**Additional context**
Used to work just fine about a few weeks ago. This bug happens to both me and a friend.

**Comment by rcelyte** [comment]
The minimum supported game version depends on the server you have selected. The minimum supported version for BeatTogether is 1.28.0.

**Comment by Tarroook** [comment]
So is there no way to play in 1.27 anymore ? I don't really mind upgrading I just generally tend to stick to older versions so I don't have any problems with mods not being up to date

**Comment by rcelyte** [comment]
Not on BeatTogether, no.

**Comment by Tarroook** [comment]
All good then, I was under the impression that the mod used peer to peer so I though it was just broken but good to know that there are dedicated servers.

**Comment by rcelyte** [comment]
Beat Saber used to use P2P, but switched to dedicated in 1.16.3. Most of the servers set up by the community can be found at https://bssb.app/master-servers
