### ISSUE TITLE
new update causing game not to launch with MultiplayerCore installed[BUG] 

### ISSUE THREAD

**Issue by YoItzXeno** [Goobwabber/MultiplayerCore#46]
latest version just downloaded it from github today

Pc, Steam I'm using steam link through the oculus to launch the game but regardless even launching through steam on my computer it won't launch

if you go through the normal steps of trying to play and have MultiplayerCore in your plugins folder with whatever other mods you have along with beat together Beatsaber gets stuck on the launch screen and doesn't proceed any further.

**To Reproduce**

1. have the mods in your plugins folder
2. try to launch through steam
3. game gets stuck on launch screen

**Expected behavior**
I expected the game to launch so i could play it with my friends with custom songs

**Log**

[_latest.log](https://github.com/Goobwabber/MultiplayerCore/files/13622520/_latest.log)

**Comment by Kevman95** [comment]
We don't support the latest game version yet. Hense the issues your describing. 

Currently PC support is only 1.29.1 we plan to support latest soon. Remove the mod if you updated.
