### ISSUE TITLE
No downloadable releases available

### ISSUE THREAD

**Issue by MagneticLlama** [Goobwabber/MultiplayerCore#6]
I am trying to set up BeatTogether for a Beat Saber 1.18.3 install. 
The README says "Download the MultiplayerCore file listed under Assets Here.", and "Here" links to the Releases page, which is currently empty.

**Comment by ColbyLeiske** [comment]
Hey, I think this `MultiplayerCore` is going to be `>1.19` (but the author can confirm that themselves). 

You may looking for https://github.com/Goobwabber/MultiplayerExtensions/releases which supports `1.18.3`.

**Comment by MagneticLlama** [comment]
Thank you, I'll close the issue.
