### ISSUE TITLE
Request 1.18

### ISSUE THREAD

**Issue by MichaelJmad** [Goobwabber/MultiplayerCore#7]
I understand that you are working on the 1.19 update and I thank you for that.
But to hold us over do you have the release for 1.18 or can I just compile the current build for 1.18?

**Comment by ColbyLeiske** [comment]
Hey, I think this MultiplayerCore is going to be >1.19 (but the author can confirm that themselves).

You may looking for https://github.com/Goobwabber/MultiplayerExtensions/releases which supports 1.18.3.

**Comment by Goobwabber** [comment]
Use MultiplayerExtensions for releases prior to 1.19.
