### ISSUE TITLE
[BUG] MultiplayerCore breaks Official Quick Play

### ISSUE THREAD

**Issue by roydejong** [Goobwabber/MultiplayerCore#8]
**MultiplayerCore Version and Download Source**
MultiplayerCore 1.0.0 `Unofficial-dev-86d5c5b`
Built from source (dev @ [86d5c5b](https://github.com/Goobwabber/MultiplayerCore/commit/86d5c5bdd948b8c5992b93ff78745f3ff8429c7c))

**Your Platform**
PC Steam, Beat Saber 1.20.0

**Describe the bug**
When MultiplayerCore is installed, Official Quick Play lobbies will not work. Specifically, when a level starts and the other players transition to the gameplay scene, the local player will be stuck in the lobby instead.

**To Reproduce**
1. Join Quick Play lobby
2. Wait for countdown to finish for level start
3. You will be stuck in lobby in the red "level is starting" fog

**Log/context**
I'm testing multiplayer mods on 1.20.0 and ran into this, but this is not a recent issue. I've seen this happen on previous dev builds of MultiplayerCore including on older game versions.

Logging around game start:
```
[INFO @ 00:44:52 | ServerBrowser/BssbMenuDataCollector] Lobby state changed to: GameStarting
[DEBUG @ 00:44:52 | MultiplayerCore/MpLevelLoader] Loading level TurnMeOn
[DEBUG @ 00:44:52 | MultiplayerCore/MpLevelDownloader] Starting download: TurnMeOn
[ERROR @ 00:44:52 | MultiplayerCore/MpLevelDownloader] Could not parse hash from id TurnMeOn
[DEBUG @ 00:44:52 | MultiplayerCore/MpLevelLoader] Loaded level TurnMeOn
```

The lobby never transitions to the `GameRunning` lobby state, which implies `HandleMultiplayerLevelLoaderCountdownFinished` is never invoked.

**Comment by Goobwabber** [comment]
this could be due to not receiving an entitlement from other players on official
i'll look into it soon

**Comment by Goobwabber** [comment]
this issue appears to be fixed now? not sure what happened

**Comment by roydejong** [comment]
I think this issue still exists to an extent, but under very particular circumstances:

When a player goes idle, i.e. takes their headset off but doesn't get kicked from the lobby (this happens somewhat regularly on public quick play), they seem to break the entitlement checks and the lobby gets "stuck" for MpCore players as described in this issue, or at least until that offending player leaves.
